name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Next.js App (frontend) and Install Backend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json
            backend/package-lock.json

      # Frontend
      - name: Install frontend dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./frontend

      # Backend
      - name: Install backend dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./backend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

  sonarqube-analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=Wiem-Ben-Araar_WiVision
            -Dsonar.organization=wiem-ben-araar
            -Dsonar.sources=frontend,backend
            -Dsonar.exclusions=**/node_modules/**,**/*.test.ts,**/*.test.js
            -Dsonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
